CREATE TABLE USERSIGNUP (
  ACCOUNTNO INT(15) NOT NULL PRIMARY KEY, -- Account Number (Auto-generated)
  ACCOUNTTYPE VARCHAR(55) NOT NULL, -- Account Type (Savings, Checking, etc.)
  FULLNAME VARCHAR(255) NOT NULL, -- Full Name of the Account Holder
  EMAIL VARCHAR(255) NOT NULL UNIQUE, -- Email (Used for login)
  PHONENUMBER VARCHAR(15) NOT NULL, -- Phone Number
  ADDRESS TEXT NOT NULL, -- User's Address
  DATEOFBIRTH DATE NOT NULL, -- Date of Birth
  GENDER VARCHAR(10) NOT NULL, -- Gender
  PASSWORD VARCHAR(255) NOT NULL, -- Hashed Password
  INITIALDEPOSIT DECIMAL(10, 2) NOT NULL, -- Initial Deposit (if applicable)
  ACCOUNTBALANCE DECIMAL(15, 2) DEFAULT 0.00, -- Account Balance (default 0)
  IFSCCODE VARCHAR(15) NOT NULL, -- IFSC Code (Auto-generated)
  BRANCHNAME VARCHAR(255) NOT NULL, -- Branch Name (Auto-generated)
  PROFILEPICTURE VARCHAR(255) DEFAULT NULL, -- Profile Picture (optional)
  SECURITYQUESTION VARCHAR(255) DEFAULT NULL, -- Security Question (optional)
  SECURITYANSWER VARCHAR(255) DEFAULT NULL, -- Security Answer (optional)
  TWOFAENABLED BOOLEAN DEFAULT FALSE, -- Two-Factor Authentication Flag
  TWOFASECRET VARCHAR(255) DEFAULT NULL, -- Two-Factor Authentication Secret
  ACCOUNTSTATUS ENUM('active', 'suspended', 'deleted') DEFAULT 'active', -- Account Status
  CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Account Creation Time
  UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP -- Account Last Update Time
);

-- Indexes for faster lookups
CREATE INDEX IDX_EMAIL ON USERSIGNUP (EMAIL);

CREATE INDEX IDX_PHONENUMBER ON USERSIGNUP (PHONENUMBER);

CREATE INDEX IDX_IFSC_CODE ON USERSIGNUP (IFSCCODE);